[package]
name = "funutd"
description = "Procedural texture library."
keywords = ["graphics"]
license = "MIT OR Apache-2.0"
version = "0.7.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
homepage = "https://github.com/SamiPerttu/funutd"
repository = "https://github.com/SamiPerttu/funutd"
readme = "README.md"
edition = "2021"

[dependencies]
glam = "0.22.0"

[dev-dependencies]
pixels = "0.11.0"
winit = "0.27.5"
winit_input_helper = "0.13.0"
egui = "0.20.1"
eframe = "0.20.1"
rayon = "1.6.1"
arboard = "3.2.0"
rfd = "0.10.0"
png = "0.17.7"

[[example]]
name = "pixel"
path = "examples/pixel.rs"

[[example]]
name = "editor"
path = "examples/editor.rs"
