[package]
name = "utd"
version = "0.1.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wrapping_arithmetic = "0.1.0"
glam = "0.9.4"
rand_core = "0.5"
rand = "0.7"
rand_krull = { path = "../rand_krull" }
