[package]
name = "utd"
version = "0.1.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.2"
enum_dispatch = "0.3.8"

[dev-dependencies]
pixels = "0.9.0"
winit = "0.26.1"
winit_input_helper = "0.11.1"
