[package]
name = "funutd"
description = "Procedural texture library."
keywords = ["graphics"]
license = "MIT OR Apache-2.0"
version = "0.3.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
homepage = "https://github.com/SamiPerttu/funutd"
repository = "https://github.com/SamiPerttu/funutd"
readme = "README.md"
edition = "2021"

[dependencies]
glam = "0.20.5"
enum_dispatch = "0.3.8"

[dev-dependencies]
pixels = "0.9.0"
winit = "0.26.1"
winit_input_helper = "0.12.0"
plotters = "0.3.1"
egui = "0.18.1"
eframe = "0.18.0"
rayon = "1.5.2"
arboard = "2.1.0"

[[example]]
name = "plot"
path = "examples/plot.rs"

[[example]]
name = "pixel"
path = "examples/pixel.rs"

[[example]]
name = "editor"
path = "examples/editor.rs"
